### ISSUE TITLE
画面幅が狭い場合、投稿欄に横スクロールバーが出現する

### ISSUE THREAD

**Issue by fiwa-wkrf** [wd-shiroma/tooterminal#2]
画面幅が狭い場合、投稿欄の下部に横スクロールバーが出現し、投稿欄全体が見渡せない。
v1系では横スクロールバーは出現せずに、投稿欄の幅は画面幅に合わせて表示されていた。

![tooterminal2_ _20180920](https://user-images.githubusercontent.com/43440086/45817674-78e6ef80-bd1a-11e8-8ec4-a3eed6253ddc.png)

**Comment by wd-shiroma** [comment]
投稿窓を固定幅に設定したのが理由です。

ターミナル画面の最小幅を今後は指定するつもりでいるので、その前対応となります
（とはいえおそまつなので、早めに対応します）

ターミナル画面の最小幅は、公式Webクライアントの情報量を元に決定したいと思います。

It is because of setting fixed width in the input form.

I will set the min-width in terminal in a few days. That's preparation for that.
(But it is inappropriate. I will solve this problem soon.)

The min-width in terminal will be decided by official web client size.

**Comment by wd-shiroma** [comment]
I fixed by pull request #4
