### ISSUE TITLE
文字の折り返しがうまく効かない場合がある

### ISSUE THREAD

**Issue by fiwa-wkrf** [wd-shiroma/tooterminal#3]
v1系とv2.0.0で、投稿の文字の折り返しが効かない場合の挙動が変わったので気になってる点です。
- v1系では、画面幅を突き抜けても画面下に横スクロールバーが出現しない。
- v2.0.0では、画面下に横スクロールバーが出現する。
- 標準WebUIでは、強制的に文字が折り返される。

※全て、今回見かけた例においての事です。
例として、v2.0.0と標準WebUIのスクリーンショットを貼っておきます。

![tooterminal _20180921](https://user-images.githubusercontent.com/43440086/45860339-9ad78500-bda1-11e8-93f7-ef3bf75aea12.png)
![mastodon _20180921](https://user-images.githubusercontent.com/43440086/45860346-a165fc80-bda1-11e8-9e13-f8d5bde13f13.png)

**Comment by fiwa-wkrf** [comment]
Issueを分けるべきか悩みましたが、似た事例として追記します。

HTLやFTLを見ている時に、別インスタンスユーザーの「@ID@インスタンス名」表示部分が、画面幅を超える場合もv2.0.0は画面下に横スクロールバーが出現するようになりました。
標準WebUIでは、画面幅に収まらない部分は表示されず、マウスオーバー時に全てが吹き出しで表示されます。

**Comment by wd-shiroma** [comment]
感嘆符が折り返されない事象についてはこちらでも確認してあります。
これはv1時代から延々と悩まされている問題でもあります。

この問題もすぐに解決したいところですが、原因の特定に時間がかかりそうなので、すぐに修正することはできません。しばらくペンディングとさせてください。

I have also recognized about the issue that the exclamation mark is not folded back.
Since v1, I have no way to fix this issue.

I want to solve this issue as soon as possible, but I will take time to identify the cause. So this issue take a few time to fix. I am going to pend this problem.
